### ISSUE TITLE
설계 가이드 라인 이슈

### ISSUE THREAD

**Issue by NarinHan** [2022OSSHAN/TeamProject#1]
주제 : 학관 메뉴 자판기

- Menu Driven 형태 : 메뉴 조회, 메뉴 추가, 메뉴 수정, 메뉴 삭제, 메뉴 검색, 메뉴 가격별 검색, 메뉴 추천, 파일 저장 등
- 구조체 형태 : 메뉴 이름, 가격, 판매 부스
- 판매 부스 별 나눌 것인지?가격 별로 나눌 것인지?
- 추가 기능 생각해보기

**Comment by NarinHan** [comment]
메뉴 조회 -> 1번) 부스 별 보기 2번) 전체보기

**Comment by NarinHan** [comment]
메뉴 추천 -> 랜덤 픽

**Comment by Kyutae02** [comment]
개발 언어: c 언어 사용

**Comment by Kyutae02** [comment]
메뉴 조회 -> 가격별 보기
