### ISSUE TITLE
데이터 저장 및 로드

### ISSUE THREAD

**Issue by Kyutae02** [2022OSSHAN/TeamProject#9]
띄어 쓰기를 받기 위해서 %[^\n]s를 사용하는데 이렇게 하면은 오류가 나더라구요 그래서 %[^\n]s. 이렇게 하여서 '.'으로 구분을 하려 합니다. 혹시 다른 방법이 있을까요?

**Comment by NarinHan** [comment]
메뉴명에 띄어쓰기가 하나만 있지 않은 경우도 있을 수 있으니...
차라리 저장할 때 메뉴명, 가격, 부스를 한 줄씩 저장하고, 한 줄씩 읽어오는 것은 어떨까요?

---- (예시) ----
제육 크림 파스타
4800
H:Plate
-------------

이렇게 저장되어 있으면 fgets 로 한 줄씩 읽어오는 것이 편하지 않을까 생각합니다~!

**Comment by Kyutae02** [comment]
제가 예전에 그렇게 하려고 했다가 실패해서.. 혹시 그 부분 맡아서 수정해주실 수 있나요?

**Comment by NarinHan** [comment]
넵 해볼게요. 하다가 실패하거나 오류나면 이슈 남길께요~!

**Comment by NarinHan** [comment]
loadData 와 saveData 함수 모두 성공적으로 구현해서 PR 했습니다.
한 줄씩 입/출력으로 구현했습니다.
(Just for reference) 출력은 fprintf, 입력은 fgets 와 fscanf 사용했습니다.
